### ISSUE TITLE
Error on Form Submissions

### ISSUE THREAD

**Issue by chris-ramsey** [xataio/xataform#19]
https://www.xataform.com/forms

Error Displayed after button submission:
table [xataform-answers:main/rec_ch9uiu5q1856u98kdsmg-v1] not found

Form is not saved in responses.

**Comment by kostasb** [comment]
@chris-ramsey thank you for the report, this is due to the hosted instance reaching user capacity. We are working to increase the relevant limits and will send an update!

**Comment by kostasb** [comment]
Hi @chris-ramsey additional capacity is available in xataform.com and you should be able to check it out now.

**Comment by alexfrancoeur** [comment]
@kostasb is this good to close if it's resolved?
